CI: Fix Cargo.toml version check

diff --git a/.github/workflows/build.yaml b/.github/workflows/build.yaml
--- a/.github/workflows/build.yaml
+++ b/.github/workflows/build.yaml
@@ -29,15 +29,17 @@ jobs:
         if: startsWith(github.ref, 'refs/tags/')
         shell: bash
         run: |
-          set -eou
-          version=$(grep '^version' Cargo.toml | awk -F' = ' '{print $2}' | tr -d '"')
-          version="v$version"
+          set -eou pipefail
           tag='${{github.ref}}'
           tag="${tag#refs/tags/}"
-          if [ "$tag" != "$version" ]; then
-            echo "::error::Git tag doesn't match the Cargo version! ($tag != $version)"
-            exit 1
-          fi
+          for file in */Cargo.toml; do
+            version=$(grep '^version' $file | head -1 | awk -F' = ' '{print $2}' | tr -d '"')
+            version="v$version"
+            if [ "$tag" != "$version" ]; then
+              echo "::error::Git tag doesn't match the Cargo version! ($tag != $version)"
+              exit 1
+            fi
+          done
       - name: Setup Rust toolchain
         uses: dtolnay/rust-toolchain@stable
         with:
